// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_splitaligner_core_info
Rcpp::List cpp_splitaligner_core_info();
RcppExport SEXP _SplitAlignerR_cpp_splitaligner_core_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_splitaligner_core_info());
    return rcpp_result_gen;
END_RCPP
}
// cpp_validate_branch_length_tokens
Rcpp::DataFrame cpp_validate_branch_length_tokens(Rcpp::CharacterVector tokens);
RcppExport SEXP _SplitAlignerR_cpp_validate_branch_length_tokens(SEXP tokensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type tokens(tokensSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_validate_branch_length_tokens(tokens));
    return rcpp_result_gen;
END_RCPP
}
// cpp_validate_species_tree
Rcpp::List cpp_validate_species_tree(std::string newick);
RcppExport SEXP _SplitAlignerR_cpp_validate_species_tree(SEXP newickSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type newick(newickSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_validate_species_tree(newick));
    return rcpp_result_gen;
END_RCPP
}
// cpp_align_branches
Rcpp::List cpp_align_branches(std::string species_newick, Rcpp::CharacterVector gene_newicks, Rcpp::CharacterVector gene_ids, std::string mode);
RcppExport SEXP _SplitAlignerR_cpp_align_branches(SEXP species_newickSEXP, SEXP gene_newicksSEXP, SEXP gene_idsSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type species_newick(species_newickSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type gene_newicks(gene_newicksSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type gene_ids(gene_idsSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_align_branches(species_newick, gene_newicks, gene_ids, mode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SplitAlignerR_cpp_splitaligner_core_info", (DL_FUNC) &_SplitAlignerR_cpp_splitaligner_core_info, 0},
    {"_SplitAlignerR_cpp_validate_branch_length_tokens", (DL_FUNC) &_SplitAlignerR_cpp_validate_branch_length_tokens, 1},
    {"_SplitAlignerR_cpp_validate_species_tree", (DL_FUNC) &_SplitAlignerR_cpp_validate_species_tree, 1},
    {"_SplitAlignerR_cpp_align_branches", (DL_FUNC) &_SplitAlignerR_cpp_align_branches, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SplitAlignerR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
