# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_splitaligner_core_info <- function() {
    .Call(`_SplitAlignerR_cpp_splitaligner_core_info`)
}

cpp_validate_branch_length_tokens <- function(tokens) {
    .Call(`_SplitAlignerR_cpp_validate_branch_length_tokens`, tokens)
}

cpp_validate_species_tree <- function(newick) {
    .Call(`_SplitAlignerR_cpp_validate_species_tree`, newick)
}

cpp_align_branches <- function(species_newick, gene_newicks, gene_ids, mode) {
    .Call(`_SplitAlignerR_cpp_align_branches`, species_newick, gene_newicks, gene_ids, mode)
}
