# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_engine002_authority_create <- function(taxon_labels, terminal_taxon_ids, primitive_splits) {
    .Call(`_SplitAlignerR_cpp_engine002_authority_create`, taxon_labels, terminal_taxon_ids, primitive_splits)
}

cpp_engine002_authority_info <- function(authority_pointer) {
    .Call(`_SplitAlignerR_cpp_engine002_authority_info`, authority_pointer)
}

cpp_engine002_authority_close <- function(authority_pointer) {
    .Call(`_SplitAlignerR_cpp_engine002_authority_close`, authority_pointer)
}

cpp_engine002_plan_encode <- function(authority_pointer, pattern_id, retained, states, primitive_queries) {
    .Call(`_SplitAlignerR_cpp_engine002_plan_encode`, authority_pointer, pattern_id, retained, states, primitive_queries)
}

cpp_engine002_plan_decode <- function(authority_pointer, record) {
    .Call(`_SplitAlignerR_cpp_engine002_plan_decode`, authority_pointer, record)
}

cpp_engine002_plan_view_snapshot <- function(authority_pointer, record) {
    .Call(`_SplitAlignerR_cpp_engine002_plan_view_snapshot`, authority_pointer, record)
}

cpp_engine002_hash_reference_vectors <- function() {
    .Call(`_SplitAlignerR_cpp_engine002_hash_reference_vectors`)
}

cpp_splitaligner_core_info <- function() {
    .Call(`_SplitAlignerR_cpp_splitaligner_core_info`)
}

cpp_validate_branch_length_tokens <- function(tokens) {
    .Call(`_SplitAlignerR_cpp_validate_branch_length_tokens`, tokens)
}

cpp_validate_species_tree <- function(newick) {
    .Call(`_SplitAlignerR_cpp_validate_species_tree`, newick)
}

cpp_align_branches <- function(species_newick, gene_newicks, gene_ids, mode) {
    .Call(`_SplitAlignerR_cpp_align_branches`, species_newick, gene_newicks, gene_ids, mode)
}
