# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_engine002_authority_create <- function(taxon_labels, terminal_taxon_ids, primitive_splits) {
    .Call(`_SplitAlignerR_cpp_engine002_authority_create`, taxon_labels, terminal_taxon_ids, primitive_splits)
}

cpp_engine002_authority_info <- function(authority_pointer) {
    .Call(`_SplitAlignerR_cpp_engine002_authority_info`, authority_pointer)
}

cpp_engine002_authority_close <- function(authority_pointer) {
    .Call(`_SplitAlignerR_cpp_engine002_authority_close`, authority_pointer)
}

cpp_engine002_plan_encode <- function(authority_pointer, pattern_id, retained, states, primitive_queries) {
    .Call(`_SplitAlignerR_cpp_engine002_plan_encode`, authority_pointer, pattern_id, retained, states, primitive_queries)
}

cpp_engine002_plan_decode <- function(authority_pointer, record) {
    .Call(`_SplitAlignerR_cpp_engine002_plan_decode`, authority_pointer, record)
}

cpp_engine002_plan_view_snapshot <- function(authority_pointer, record) {
    .Call(`_SplitAlignerR_cpp_engine002_plan_view_snapshot`, authority_pointer, record)
}

cpp_engine002_plan_view_probe <- function(authority_pointer, record, primitive_ids, repeats) {
    .Call(`_SplitAlignerR_cpp_engine002_plan_view_probe`, authority_pointer, record, primitive_ids, repeats)
}

cpp_engine002_hash_reference_vectors <- function() {
    .Call(`_SplitAlignerR_cpp_engine002_hash_reference_vectors`)
}

cpp_engine002_large_offset_arithmetic_probe <- function(record_bytes_value, pattern_count_value) {
    .Call(`_SplitAlignerR_cpp_engine002_large_offset_arithmetic_probe`, record_bytes_value, pattern_count_value)
}

cpp_engine002_memory_store_create <- function(authority_pointer, pattern_count) {
    .Call(`_SplitAlignerR_cpp_engine002_memory_store_create`, authority_pointer, pattern_count)
}

cpp_engine002_disk_store_create <- function(authority_pointer, retained_patterns, directory, run_store_id, cache_budget, scratch_budget, index_budget, metadata_budget, combined_runtime_bound) {
    .Call(`_SplitAlignerR_cpp_engine002_disk_store_create`, authority_pointer, retained_patterns, directory, run_store_id, cache_budget, scratch_budget, index_budget, metadata_budget, combined_runtime_bound)
}

cpp_engine002_disk_store_open <- function(authority_pointer, manifest_path, cache_budget, scratch_budget, index_budget, metadata_budget, combined_runtime_bound) {
    .Call(`_SplitAlignerR_cpp_engine002_disk_store_open`, authority_pointer, manifest_path, cache_budget, scratch_budget, index_budget, metadata_budget, combined_runtime_bound)
}

cpp_engine002_store_insert <- function(store_pointer, record) {
    .Call(`_SplitAlignerR_cpp_engine002_store_insert`, store_pointer, record)
}

cpp_engine002_store_finalize <- function(store_pointer, directory, run_store_id) {
    .Call(`_SplitAlignerR_cpp_engine002_store_finalize`, store_pointer, directory, run_store_id)
}

cpp_engine002_store_lookup_snapshot <- function(store_pointer, pattern_id, retained) {
    .Call(`_SplitAlignerR_cpp_engine002_store_lookup_snapshot`, store_pointer, pattern_id, retained)
}

cpp_engine002_store_debug_pin <- function(store_pointer, pattern_id, retained) {
    .Call(`_SplitAlignerR_cpp_engine002_store_debug_pin`, store_pointer, pattern_id, retained)
}

cpp_engine002_pin_release <- function(pin_pointer) {
    .Call(`_SplitAlignerR_cpp_engine002_pin_release`, pin_pointer)
}

cpp_engine002_store_stats <- function(store_pointer) {
    .Call(`_SplitAlignerR_cpp_engine002_store_stats`, store_pointer)
}

cpp_engine002_store_close <- function(store_pointer) {
    .Call(`_SplitAlignerR_cpp_engine002_store_close`, store_pointer)
}

cpp_engine002_set_publication_failpoint <- function(stage) {
    .Call(`_SplitAlignerR_cpp_engine002_set_publication_failpoint`, stage)
}

cpp_splitaligner_core_info <- function() {
    .Call(`_SplitAlignerR_cpp_splitaligner_core_info`)
}

cpp_validate_branch_length_tokens <- function(tokens) {
    .Call(`_SplitAlignerR_cpp_validate_branch_length_tokens`, tokens)
}

cpp_validate_species_tree <- function(newick) {
    .Call(`_SplitAlignerR_cpp_validate_species_tree`, newick)
}

cpp_align_branches <- function(species_newick, gene_newicks, gene_ids, mode) {
    .Call(`_SplitAlignerR_cpp_align_branches`, species_newick, gene_newicks, gene_ids, mode)
}
